import AppKit

/// One thumbnail cell in the switcher — app icon, live window snapshot, title.
/// Also owns its own mouse tracking: hovering (real cursor motion only, never
/// a resting cursor a new tracking area happens to appear under) previews the
/// selection, clicking switches immediately.
private final class SwitcherCellView: NSView {
    private let iconView = NSImageView()
    private let thumbView = NSImageView()
    private let titleLabel = NSTextField(labelWithString: "")
    private let card = NSView()
    private let dirtyDot = NSView()
    private var trackingArea: NSTrackingArea?

    /// Fires only from an actual `mouseMoved` event — that event type is only
    /// ever generated by real pointer motion, never synthesized just because
    /// this view (and its tracking area) appeared under an already-stationary
    /// cursor. That's what keeps "I pressed Cmd+Tab with the mouse sitting
    /// over some card" from silently hijacking the selection.
    var onHover: (() -> Void)?
    var onClick: (() -> Void)?

    var isSelected: Bool = false {
        didSet { updateSelectionAppearance() }
    }

    /// "Something changed here while you weren't looking" — a small accent
    /// dot in the corner, matching a Dock-badge/notification-style affordance.
    var isDirty: Bool = false {
        didSet { dirtyDot.isHidden = !isDirty }
    }

    override init(frame frameRect: NSRect) {
        super.init(frame: frameRect)
        wantsLayer = true

        card.wantsLayer = true
        card.layer?.cornerRadius = 12
        card.layer?.borderWidth = 2
        addSubview(card)

        thumbView.imageScaling = .scaleProportionallyUpOrDown
        thumbView.wantsLayer = true
        thumbView.layer?.cornerRadius = 6
        thumbView.layer?.masksToBounds = true
        addSubview(thumbView)

        iconView.imageScaling = .scaleProportionallyUpOrDown
        addSubview(iconView)

        titleLabel.alignment = .center
        titleLabel.font = .systemFont(ofSize: 12, weight: .medium)
        titleLabel.textColor = .white
        titleLabel.lineBreakMode = .byTruncatingTail
        addSubview(titleLabel)

        dirtyDot.wantsLayer = true
        dirtyDot.layer?.backgroundColor = NSColor.systemBlue.cgColor
        dirtyDot.layer?.cornerRadius = 5
        dirtyDot.layer?.borderWidth = 1.5
        dirtyDot.layer?.borderColor = NSColor.black.withAlphaComponent(0.5).cgColor
        dirtyDot.isHidden = true
        addSubview(dirtyDot)

        updateSelectionAppearance()
    }

    required init?(coder: NSCoder) { fatalError() }

    func configure(icon: NSImage?, thumbnail: NSImage?, title: String) {
        titleLabel.stringValue = title
        if let thumbnail {
            // Real live preview — small icon badge in the corner, big thumbnail on top.
            thumbView.image = thumbnail
            iconView.image = icon
            iconView.isHidden = false
            iconIsFallback = false
        } else {
            // No Screen Recording permission (yet) — show a big icon instead
            // of leaving the card looking broken/empty.
            thumbView.image = nil
            iconView.image = icon
            iconIsFallback = true
        }
        needsLayout = true
    }

    private var iconIsFallback = false

    private func updateSelectionAppearance() {
        card.layer?.backgroundColor = (isSelected ? NSColor.white.withAlphaComponent(0.16) : NSColor.white.withAlphaComponent(0.05)).cgColor
        card.layer?.borderColor = (isSelected ? NSColor.white.withAlphaComponent(0.9) : NSColor.clear).cgColor
    }

    override func layout() {
        super.layout()
        card.frame = bounds
        let thumbH: CGFloat = 84
        titleLabel.frame = NSRect(x: 6, y: 4, width: bounds.width - 12, height: 16)
        dirtyDot.frame = NSRect(x: bounds.width - 16, y: bounds.height - 16, width: 10, height: 10)

        if iconIsFallback {
            // No thumbnail available: one big centered icon fills the card.
            thumbView.frame = .zero
            let size: CGFloat = 56
            iconView.frame = NSRect(x: bounds.width / 2 - size / 2, y: 26 + (thumbH - size) / 2, width: size, height: size)
        } else {
            thumbView.frame = NSRect(x: 10, y: bounds.height - thumbH - 10, width: bounds.width - 20, height: thumbH)
            iconView.frame = NSRect(x: bounds.width / 2 - 12, y: 26, width: 24, height: 24)
        }
    }

    // MARK: - Mouse

    override func updateTrackingAreas() {
        super.updateTrackingAreas()
        if let trackingArea { removeTrackingArea(trackingArea) }
        // .mouseMoved (not .mouseEnteredAndExited) is the whole point: it is
        // only ever delivered from genuine pointer motion, so a resting
        // cursor that happens to already sit over this card when the panel
        // appears never triggers a hover callback.
        let area = NSTrackingArea(rect: bounds, options: [.mouseMoved, .activeAlways, .inVisibleRect], owner: self, userInfo: nil)
        addTrackingArea(area)
        trackingArea = area
    }

    // Capture clicks/moves at the cell level regardless of which child
    // (icon/thumbnail/title) the point technically falls over — AppKit mouse
    // events don't bubble up on their own, so without this a click on the
    // thumbnail image view would silently go nowhere.
    override func hitTest(_ point: NSPoint) -> NSView? {
        super.hitTest(point) != nil ? self : nil
    }

    override func mouseMoved(with event: NSEvent) {
        onHover?()
    }

    override func mouseDown(with event: NSEvent) {
        onClick?()
    }
}

protocol SwitcherOverlayDelegate: AnyObject {
    func switcherOverlay(_ overlay: SwitcherOverlay, didHoverIndex index: Int)
    func switcherOverlay(_ overlay: SwitcherOverlay, didClickIndex index: Int)
    /// A mouse click landed anywhere that isn't a card — another app's
    /// window, the desktop, or empty space inside the panel itself. Dismiss,
    /// same as Esc, without switching anywhere.
    func switcherOverlayDidClickOutside(_ overlay: SwitcherOverlay)
}

/// Borderless, floating overlay that lists every on-screen window as a row of
/// cards — press-and-hold Cmd, tap Tab (or move the mouse) to move the
/// highlight, release Cmd (or click a card) to switch. Mirrors the muscle
/// memory of Windows' Alt+Tab, plus optional mouse control.
final class SwitcherOverlay {
    weak var delegate: SwitcherOverlayDelegate?

    private let panel: NSPanel
    private let stack = NSStackView()
    private var cells: [SwitcherCellView] = []
    private var globalClickMonitor: Any?
    private var localClickMonitor: Any?

    init() {
        panel = NSPanel(
            contentRect: .zero,
            styleMask: [.nonactivatingPanel, .borderless],
            backing: .buffered,
            defer: false
        )
        panel.level = .popUpMenu
        panel.isOpaque = false
        panel.backgroundColor = .clear
        panel.hasShadow = true
        // Nonactivating panel: clicks/moves are still delivered to our views,
        // but the panel never steals key/main status or activates this
        // background app — whatever app you're Cmd+Tab-ing away from stays
        // "active" the whole time, exactly as real Alt+Tab behaves.
        panel.ignoresMouseEvents = false
        panel.acceptsMouseMovedEvents = true
        panel.collectionBehavior = [.canJoinAllSpaces, .stationary, .fullScreenAuxiliary]

        let background = NSVisualEffectView()
        background.material = .hudWindow
        background.state = .active
        background.wantsLayer = true
        background.layer?.cornerRadius = 18
        background.blendingMode = .behindWindow

        stack.orientation = .horizontal
        stack.spacing = 10
        stack.edgeInsets = NSEdgeInsets(top: 16, left: 16, bottom: 16, right: 16)

        panel.contentView = background
        background.addSubview(stack)
        stack.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            stack.leadingAnchor.constraint(equalTo: background.leadingAnchor),
            stack.trailingAnchor.constraint(equalTo: background.trailingAnchor),
            stack.topAnchor.constraint(equalTo: background.topAnchor),
            stack.bottomAnchor.constraint(equalTo: background.bottomAnchor),
        ])
    }

    var isVisible: Bool { panel.isVisible }

    func show(windows: [WindowInfo], selected: Int, dirty: Set<CGWindowID> = []) {
        cells.forEach { $0.removeFromSuperview() }
        cells.removeAll()

        let cellSize = NSSize(width: 150, height: 128)
        for (index, window) in windows.enumerated() {
            let cell = SwitcherCellView(frame: NSRect(origin: .zero, size: cellSize))
            cell.widthAnchor.constraint(equalToConstant: cellSize.width).isActive = true
            cell.heightAnchor.constraint(equalToConstant: cellSize.height).isActive = true
            let icon = NSRunningApplication(processIdentifier: window.pid)?.icon
            let thumb = Snapshot.thumbnail(for: window.windowID)
            let title = window.title.isEmpty ? window.ownerName : window.title
            cell.configure(icon: icon, thumbnail: thumb, title: title)
            cell.isDirty = dirty.contains(window.windowID)
            cell.onHover = { [weak self] in
                guard let self else { return }
                self.delegate?.switcherOverlay(self, didHoverIndex: index)
            }
            cell.onClick = { [weak self] in
                guard let self else { return }
                self.delegate?.switcherOverlay(self, didClickIndex: index)
            }
            stack.addArrangedSubview(cell)
            cells.append(cell)
        }

        let width = CGFloat(cells.count) * (cellSize.width + stack.spacing) + 32 - stack.spacing
        let height = cellSize.height + 32
        if let screen = NSScreen.main {
            let x = screen.frame.midX - width / 2
            let y = screen.frame.midY - height / 2
            panel.setFrame(NSRect(x: x, y: y, width: max(width, 0), height: height), display: true)
        }

        updateSelection(selected)
        panel.orderFrontRegardless()
        installOutsideClickMonitors()
    }

    func updateSelection(_ index: Int) {
        for (i, cell) in cells.enumerated() {
            cell.isSelected = (i == index)
        }
    }

    func hide() {
        panel.orderOut(nil)
        removeOutsideClickMonitors()
    }

    // MARK: - Click-outside-to-dismiss

    private func installOutsideClickMonitors() {
        removeOutsideClickMonitors()

        // Clicks that land in another application's window/the desktop never
        // reach our own app at all — only a *global* monitor sees those.
        globalClickMonitor = NSEvent.addGlobalMonitorForEvents(matching: [.leftMouseDown, .rightMouseDown]) { [weak self] _ in
            guard let self else { return }
            self.delegate?.switcherOverlayDidClickOutside(self)
        }

        // Clicks inside our own panel that *aren't* on a card (the padding
        // margin, or between cards) still need to dismiss — a local monitor
        // observes those without swallowing the event, so a genuine card
        // click still reaches SwitcherCellView.mouseDown normally too
        // (calling hide() twice from switchToSelected's own path is harmless).
        localClickMonitor = NSEvent.addLocalMonitorForEvents(matching: [.leftMouseDown, .rightMouseDown]) { [weak self] event in
            guard let self else { return event }
            self.delegate?.switcherOverlayDidClickOutside(self)
            return event
        }
    }

    private func removeOutsideClickMonitors() {
        if let globalClickMonitor { NSEvent.removeMonitor(globalClickMonitor) }
        if let localClickMonitor { NSEvent.removeMonitor(localClickMonitor) }
        globalClickMonitor = nil
        localClickMonitor = nil
    }
}

enum Snapshot {
    static func thumbnail(for windowID: CGWindowID) -> NSImage? {
        guard let cgImage = CGWindowListCreateImage(
            .null,
            .optionIncludingWindow,
            windowID,
            [.boundsIgnoreFraming, .nominalResolution]
        ) else {
            NSLog("CmdTabSwitcher: no thumbnail for window \(windowID) — Screen Recording permission likely missing/stale")
            return nil
        }
        return NSImage(cgImage: cgImage, size: NSSize(width: cgImage.width, height: cgImage.height))
    }
}
